server:
  replicaCount: 0
  image:
    repository: registry.baloise.dev/cat/cat-server
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat-server.apps.baloise.dev
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: DATABASE_URL
      value: tbd
    - name: DATABASE_USER
      value: tbd
    - name: DATABASE_PASS
      value: tbd

frontent:
  replicaCount: 0
  image:
    repository: registry.baloise.dev/cat/cat-frontend
    tag: latest
  network:
    http:
      servicePort: 8080
      ingress:
        host: cat.apps.baloise.dev
  env:
    - name: CAT_API_URL
      value: http://cat-server.apps.baloise.dev


