name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 12
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache local Maven repository
      uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B -Pproduction install --file pom.xml

    - name: Build & Push Docker Server
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: balcodecampcat/cat-server
      run: |
        cd cat-server
        docker build -t $DOCKER_REPO:${{ github.sha }} .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_REPO:${{ github.sha }}
    - name: Build & Push Docker Client
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPO: balcodecampcat/cat-frontend-vaadin
      run: |
        cd cat-vaadin-client
        docker build -t $DOCKER_REPO:${{ github.sha }} .
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push $DOCKER_REPO:${{ github.sha }}
    - name: Deploy Server to OpenShift
      if: github.ref == 'refs/heads/master'
      env:
        GITOPSCLI_TOKEN: ${{ secrets.GITOPSCLI_TOKEN }}
      run: |
        docker run --rm baloise/gitopscli:4.1.1 deploy \
          --git-provider "github" \
          --username "CAN BE ANYTHING IF USING GITHUB TOKEN" \
          --password "$GITOPSCLI_TOKEN" \
          --git-user "gitopscli" \
          --git-email "gitopscli@baloise.dev" \
          --organisation "baloise-incubator" \
          --repository "codes-and-texts-deployment" \
          --file "codes-and-texts/values.yaml" \
          --values "{catserver.image.tag: ${{ github.sha }}}"
    - name: Deploy Client to OpenShift
      if: github.ref == 'refs/heads/master'
      env:
        GITOPSCLI_TOKEN: ${{ secrets.GITOPSCLI_TOKEN }}
      run: |
        docker run --rm baloise/gitopscli:4.1.1 deploy \
          --git-provider "github" \
          --username "CAN BE ANYTHING IF USING GITHUB TOKEN" \
          --password "$GITOPSCLI_TOKEN" \
          --git-user "gitopscli" \
          --git-email "gitopscli@baloise.dev" \
          --organisation "baloise-incubator" \
          --repository "codes-and-texts-deployment" \
          --file "codes-and-texts/values.yaml" \
          --values "{frontend-vaadin.image.tag: ${{ github.sha }}}"
